[[languages.cpp.environments]]
CXX = "g++-12"
CXXFLAGS = [
    "-std=gnu++20",
    "-Wno-misleading-indentation",
    "-Wall",
    "-Wextra",
    "-fconcepts-diagnostics-depth=5",
    "-Wno-char-subscripts",
    "-fsplit-stack",
    "-ftrapv",
    "-fstack-protector-all",
    "-Wconversion",
    "-Wfloat-equal",
    "-D_GLIBCXX_DEBUG",
    "-O2"
]
