[[languages.cpp.environments]]
CXX = "g++-12"
CXXFLAGS = [
    "-std=gnu++20",
    "-fdiagnostics-color=always",
    "-Wno-misleading-indentation",
    "-Wall",
    "-Wextra",
    "-fconcepts-diagnostics-depth=5",
    "-Wno-char-subscripts",
    "-fsplit-stack",
    "-O2",
    "-I/home/uni_kakurenbo/CompetitiveProgramming/sources/libraries/original",
    "-I/home/uni_kakurenbo/CompetitiveProgramming/sources/libraries/original/debugger"
]
