[[languages.cpp.environments]]
CXX = "g++-13"
CXXFLAGS = [
    "-std=gnu++20",
    "-Wno-misleading-indentation",
    "-Wall",
    "-Wextra",
    "-Wdangling-reference",
    "-fconcepts-diagnostics-depth=5",
    "-Wno-char-subscripts",
    "-fsplit-stack",
    "-O2"
]
