name: analysis
run-name: ${{ github.workflow }} (${{ github.ref_name }})

on:
    workflow_call:
    workflow_dispatch:

jobs:
    lint:
        runs-on: ${{ vars.RUNNER_IMAGE }}

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref || github.ref_name }}
                  fetch-depth: 0
                  #token: Never specify GH_PAT to avoid infinite loop

            - name: Install cppcheck
              run: sudo apt install cppcheck

            - name: Run lint (default branch)
              if: ${{ github.ref_name == github.event.repository.default_branch }}
              run: cppcheck --max-ctu-depth=32 -j $(nproc) --xml --xml-version=2 -I . --output-file=./cppcheck_report.xml --enable=all .

            - name: Run lint (other branches)
              if: ${{ github.ref_name != github.event.repository.default_branch }}
              run: |
                  cppcheck --max-ctu-depth=32 -j $(nproc) -I . --output-file=./cppcheck_report.txt --enable=all .
                  cat ./cppcheck_report.txt

            - name: Push report
              if: ${{ github.ref_name == github.event.repository.default_branch }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  set -eu

                  git remote set-url origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}

                  git config --global user.name "GitHub"
                  git config --global user.email "noreply@github.com"

                  git add ./cppcheck_report.xml

                  if (git diff --cached --shortstat | grep '[0-9]'); then
                    git commit -m "[auto-verifier] lint commit ${GITHUB_SHA}"

                    REPOSITORY_NAME="${{ github.head_ref || github.ref_name }}"

                    git pull --rebase origin "${REPOSITORY_NAME}"
                    git push origin "HEAD:${REPOSITORY_NAME}"
                  else
                    echo "No updated reports."
                  fi
