name: code-analysis
run-name: ${{ github.workflow }} (${{ github.ref_name }})

on: 
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ${{ vars.RUNNER_IMAGE }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run cppcheck
        run : |
              sudo apt install cppcheck
              cppcheck --max-ctu-depth=4 -I . --output-file=cppcheck_report.txt --enable=all .

      - name: Publish report
        if: ${{ !cancelled() && github.ref_name == github.event.repository.default_branch }}
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ github.event.repository.default_branch }}
