name: analysis
run-name: ${{ github.workflow }} (${{ github.ref_name }})

on:
    workflow_call:
    workflow_dispatch:

jobs:
    lint:
        runs-on: ${{ vars.RUNNER_IMAGE }}

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Install cppcheck
              run: sudo apt install cppcheck

            - name: Run lint
              working-directory: ./.verify-helper/
              run: |
                  mkdir -p ./lint
                  cppcheck --max-ctu-depth=32 -j $(nproc) --xml -I .. --output-file=./cppcheck_report.xml --enable=all ..
                  cppcheck-htmlreport --file=cppcheck_report.xml --title=Lint --report-dir=./lint

            - name: Push report
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  git remote set-url origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}

                  git config --global user.name "GitHub"
                  git config --global user.email "noreply@github.com"

                  git add ./lint
                  git add ./cppcheck_report.txt

                  if (git diff --cached --shortstat | grep '[0-9]'); then
                    git commit -m "[auto-verifier] lint commit ${GITHUB_SHA}"
                    git pull --rebase
                    git push origin HEAD:${GITHUB_REF}
                  else
                    echo "No updated reports."
                  fi
