name: code-analysis
run-name: ${{ github.workflow }} (${{ github.ref_name }})

on: 
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ${{ vars.RUNNER_IMAGE }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: main

      - name: Run cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          other_options: -I .\main --check-config

      - name: Publish report
        if: ${{ !cancelled() && github.ref_name == github.event.repository.default_branch }}
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ github.event.repository.default_branch }}
