name: cache-clear
run-name: ${{ github.workflow }} (${{ github.ref_name }})

on:
  workflow_dispatch:
    inputs:
      prefix:
        type: string
        default: ''
        required: false

jobs:
  clear:
    runs-on: ${{ vars.RUNNER_IMAGE }}
    steps:
      - uses: snnaplab/delete-branch-cache-action@v1
        with:
          github-token: ${{ secrets.GH_PAT }}
          key: ${{ inputs.prefix }}
