name: documentation
run-name: ${{ github.workflow }} (${{ github.ref_name }})

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      GH_PAT:
        required: true

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ${{ vars.RUNNER_IMAGE }}

    steps:
    - name: Git checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        path: main

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.0

    - name: Install oj-verify
      run: pip3 install -U online-judge-verify-helper

    - name: Clone AC-Library
      uses: actions/checkout@v3
      with:
        repository: atcoder/ac-library
        sparse-checkout: atcoder
        path: ac-library

    - name: Git pull
      working-directory: main
      run: git pull --rebase

    - name: Generate documentation
      working-directory: main
      env:
        CPLUS_INCLUDE_PATH: ${{ github.workspace }}/ac-library
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        echo '::group::oj-verify docs'
        time oj-verify docs --jobs $(nproc)
        echo '::endgroup::'

  # build:
  #   runs-on: ubuntu-latest
  #   needs: generate

    # steps:
    # - name: Git checkout
    #   uses: actions/checkout@v3

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
        working-directory: ./main/.verify-helper/markdown

    - name: Build HTML
      working-directory: ./main/.verify-helper/markdown
      run: |
        bundle install
        bundle exec jekyll build -I -d ${{ github.workspace }}/_site/ --baseurl /${{ github.event.repository.name }}/

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2

  deploy:
    runs-on: ${{ vars.RUNNER_IMAGE }}
    needs: generate

    permissions:
      token-id: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
