name: cppcheck-action-test
on: 
  workflow_call:
  workflow_dispatch:

jobs:
  cppcheck:
    runs-on: ${{ vars.RUNNER_IMAGE }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}

      - name: Publish report    
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ github.event.repository.default_branch }}
