name: _cache
run-name: ${{ github.workflow }} (${{ github.ref_name }})

on:
  workflow_call:
    outputs:
      verify-status:
        value: ${{ jobs.verify.outputs.status }}
      docs-updated:
        value: ${{ jobs.docs.outputs.updated }}
    secrets:
      GH_PAT:
        required: true

jobs:
  analysis:
    runs-on: ${{ vars.RUNNER_IMAGE }}
    outputs:
      status: ${{ steps.compare.outputs.status }}

    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
      with:
        path: main

    - name: Compute hash
      run: |
        set -eu

        find ./main/ -type f -name '*.cpp' -or -name '*.hpp' | sort > ./file-list.txt

        cat ./file-list.txt | xargs sha1sum > ./cache-list.txt
        sha1sum ./cache-list.txt | cut -d ' ' -f 1 > ./hash.txt

        echo "::group::Source files [$(cat ./hash.txt)]"
        cat ./cache-list.txt;
        echo '::endgroup'

    - name: Load previous source files hash
      uses: dawidd6/action-download-artifact@v3
      with:
        name: analysis-files-hash
        path: ./prev/
        workflow_conclusion: ''
        branch: ${{ github.ref_name }}
        search_artifacts: true
        if_no_artifact_found: ignore
        github_token: ${{ secrets.GH_PAT }}

    - name: Compare cached hash
      id: compare
      working-directory: ./main/.github/workflows/internal/
      run: bash ./hash-compare.sh

    - name: Upload analysis files hash
      uses: actions/upload-artifact@v3
      with:
        name: --analysis-files-hash
        path: ./hash.txt

  verify:
    runs-on: ${{ vars.RUNNER_IMAGE }}
    outputs:
      status: ${{ steps.compare.outputs.status }}

    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
      with:
        path: main

    - name: Compute hash
      run: |
        set -eu

        find ./main/ -type f -name '*.cpp' -or -name '*.hpp' | sort > ./file-list.txt

        echo './main/.github/workflows/internal/options.env' >> ./file-list.txt
        echo './main/.github/workflows/internal/allocate.sh' >> ./file-list.txt
        echo './main/.github/workflows/internal/run-test.sh' >> ./file-list.txt
        echo './main/.github/workflows/verify.yml' >> ./file-list.txt

        cat ./file-list.txt | xargs sha1sum > ./cache-list.txt
        sha1sum ./cache-list.txt | cut -d ' ' -f 1 > ./hash.txt

        echo "::group::Source files [$(cat ./hash.txt)]"
        cat ./cache-list.txt;
        echo '::endgroup'

    - name: Load previous source files hash
      uses: dawidd6/action-download-artifact@v3
      with:
        name: verify-files-hash
        path: ./prev/
        workflow_conclusion: ''
        branch: ${{ github.ref_name }}
        search_artifacts: true
        if_no_artifact_found: ignore
        github_token: ${{ secrets.GH_PAT }}

    - name: Compare cached hash
      id: compare
      working-directory: ./main/.github/workflows/internal/
      run: bash ./hash-compare.sh

    - name: Upload verify files hash
      uses: actions/upload-artifact@v3
      with:
        name: --verify-files-hash
        path: ./hash.txt

  docs:
    runs-on: ${{ vars.RUNNER_IMAGE }}
    outputs:
      updated: ${{ steps.compare.outputs.differed }}

    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
      with:
        path: main

    - name: Compute hash
      run: |
        set -eu

        find ./main/ -type f -name '*.cpp' -or -name '*.hpp' | sort > ./file-list.txt

        find ./main/.verify-helper/docs/ -type f | sort >> ./file-list.txt
        echo './main/.github/workflows/gen-docs.yml' >> ./file-list.txt

        cat ./file-list.txt | xargs sha1sum >> ./cache-list.txt
        sha1sum ./cache-list.txt | cut -d ' ' -f 1 > ./hash.txt

        echo "::group::Docs [$(cat ./hash.txt)]"
        cat ./cache-list.txt;
        echo '::endgroup'

    - name: Load previous docs hash
      uses: dawidd6/action-download-artifact@v3
      with:
        name: docs-files-hash
        path: ./prev/
        workflow_conclusion: ''
        branch: ${{ github.ref_name }}
        search_artifacts: true
        if_no_artifact_found: ignore
        github_token: ${{ secrets.GH_PAT }}

    - name: Compare cached hash
      id: compare
      working-directory: ./main/.github/workflows/internal/
      run: bash ./hash-compare.sh

    - name: Upload docs hash
      uses: actions/upload-artifact@v3
      with:
        name: --docs-files-hash
        path: ./hash.txt
