name: _cash
run-name: ${{ github.workflow }} (${{ github.ref_name }})

on:
  workflow_call:
    outputs:
      verify-status:
        value: ${{ jobs.verify.outputs.status }}
      docs-updated:
        value: ${{ jobs.docs.outputs.updated }}

jobs:
  verify:
    runs-on: ${{ vars.RUNNER_IMAGE }}
    outputs:
      status: ${{ steps.compare.outputs.status }}

    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
      with:
        path: main

    - name: Compute hash
      run: |
        set -eu

        find ./main/ -type f -name '*.cpp' -or -name '*.hpp' | sort > ./file-list.txt
        cat ./file-list.txt | xargs sha1sum > ./cache-list.txt
        sha1sum ./cache-list.txt | cut -d ' ' -f 1 > ./hash.txt

        echo "::group::Source files [$(cat ./hash.txt)]"
        cat ./cache-list.txt;
        echo '::endgroup'

    - name: Load previous source files hash
      uses: dawidd6/action-download-artifact@v3
      with:
        name: source-files-hash
        path: ./prev/
        workflow_conclusion: ''
        search_artifacts: true
        if_no_artifact_found: ignore

    - name: Compare cached hash
      id: compare
      run: |
        set +e

        touch ./prev/hash.txt

        diff -q ./hash.txt ./prev/hash.txt
        DIFFERED="$?"

        STATUS=""
        if [ "${DIFFERED}" == '0' ]; then
          STATUS=$(cat ./prev/status.txt)
        fi

        echo "Differed: ${DIFFERED}"
        echo "Status: ${STATUS}"

        echo "status=${STATUS}" >> ${GITHUB_OUTPUT}

    - name: Upload sorce files hash
      uses: actions/upload-artifact@v3
      with:
        name: --source-files-hash
        path: ./hash.txt

  docs:
    runs-on: ${{ vars.RUNNER_IMAGE }}
    outputs:
      updated: ${{ steps.compare.outputs.differed }}

    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
      with:
        path: main

    - name: Compute hash
      run: |
        set -eu

        find ./main/ -type f -name '*.cpp' -or -name '*.hpp' | sort > ./file-list.txt
        find ./main/.verify-helper/docs/ -type f | sort >> ./file-list.txt
        cat ./file-list.txt | xargs sha1sum >> ./cache-list.txt
        sha1sum ./cache-list.txt | cut -d ' ' -f 1 > ./hash.txt

        echo "::group::Docs [$(cat ./hash.txt)]"
        cat ./cache-list.txt;
        echo '::endgroup'

    - name: Load previous docs hash
      uses: dawidd6/action-download-artifact@v3
      with:
        name: docs-files-hash
        path: ./prev/
        workflow_conclusion: ''
        search_artifacts: true
        if_no_artifact_found: ignore

    - name: Compare cached hash
      id: compare
      run: |
        set +e

        touch ./prev/hash.txt

        diff -q ./hash.txt ./prev/hash.txt
        DIFFERED="$?"

        STATUS=""
        if [ "${DIFFERED}" == '0' ]; then
          STATUS=$(cat ./prev/status.txt)
        fi

        echo "Differed: ${DIFFERED}"
        echo "differed=${DIFFERED}" >> ${GITHUB_OUTPUT}

    - name: Upload docs hash
      uses: actions/upload-artifact@v3
      with:
        name: --docs-files-hash
        path: ./hash.txt
