name: _cash-update
run-name: ${{ github.workflow }} (${{ github.ref_name }})

on:
  workflow_call:
    inputs:
      status:
        type: string
        required: true

jobs:
  save-status:
    runs-on: ${{ vars.RUNNER_IMAGE }}

    steps:
    - name: Load previous source files hash
      uses: actions/download-artifact@v3
      with:
        name: --source-files-hash
        path: ./

    - name: Save status
      run: |
        echo "Status: ${{ inputs.status }}"
        echo "${{ inputs.status }}" > ./status.txt

    - name: Upload sorce files hash
      uses: actions/upload-artifact@v3
      with:
        name: source-files-hash
        path: |
          ./hash.txt
          ./status.txt
