name: _post-cache
run-name: ${{ github.workflow }} (${{ github.ref_name }})

on:
    workflow_call:
        inputs:
            status:
                type: string
                required: true
            key:
                type: string
                required: true

jobs:
    save-status:
        name: save-status (${{ inputs.key }})
        runs-on: ${{ vars.RUNNER_IMAGE }}

        steps:
            - name: Load previous hash
              uses: actions/download-artifact@v4
              with:
                  name: --${{ inputs.key }}-files-hash
                  path: ./

            - name: Save status
              run: |
                  set -eu

                  echo "Status: ${{ inputs.status }}"
                  echo "${{ inputs.status }}" > ./status.txt

            - name: Upload hash and status
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ inputs.key }}-files-hash
                  path: |
                      ./hash.txt
                      ./status.txt
