name: _cache
run-name: ${{ github.workflow }} (${{ github.ref_name }})

on:
  workflow_call:
    inputs:
      status:
        type: string
        required: true
      key:
        type: string
        requires: true

jobs:
  save-status:
    runs-on: ${{ vars.RUNNER_IMAGE }}

    steps:
    - name: Load previous hash
      uses: actions/download-artifact@v3
      with:
        name: --${{ inputs.key }}
        path: ./

    - name: Save status
      run: |
        echo "Status: ${{ inputs.status }}"
        echo "${{ inputs.status }}" > ./status.txt

    - name: Upload hash and status
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.key }}
        path: |
          ./hash.txt
          ./status.txt
