name: library-update
run-name: ${{ github.workflow }} (${{ github.ref_name }})

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: update-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyze:
    #needs: cache
    if: ${{ !cancelled() && needs.cache.outputs.source-files-updated != '0' }}
    uses: ./.github/workflows/analyze.yml

  verify:
    #needs: cache
    if: >-
      ${{ !cancelled() &&
        needs.cache.outputs.source-files-updated != '0' &&
        github.ref_name == github.event.repository.default_branch
      }}
    uses: ./.github/workflows/verify.yml
    secrets: inherit

  documantaion:
    needs:
    #  - cache
      - analyze
      - verify
    if: >-
      ${{ !cancelled() &&
        needs.cache.outputs.docs-updated != '0' &&
        github.ref_name == github.event.repository.default_branch
      }}
    uses: ./.github/workflows/gen-docs.yml
    secrets: inherit
