name: library-update
run-name: ${{ github.workflow }} (${{ github.ref_name }})

on:
  workflow_dispatch:
    inputs:
      force:
        type: boolean
        default: true
        required: true
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: update-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cache:
    if: ${{ ! github.event.inputs.force }}
    uses: ./.github/workflows/cache--load-status.yml

  quit:
    needs: cache
    if: eeds.cache.outputs.verify-status == 'failure'
    steps:
    - run: exit 1

  analyze:
    needs: cache
    if: >-
      ${{
        !cancelled() &&
        (
          needs.cache.outputs.verify-status == '' ||
          github.event.inputs.force
        )
      }}
    uses: ./.github/workflows/analyze.yml

  verify:
    needs: cache
    if: >-
      ${{
        !cancelled() &&
        (
          needs.cache.outputs.verify-status == '' ||
          github.event.inputs.force
        ) &&
        github.ref_name == github.event.repository.default_branch
      }}
    uses: ./.github/workflows/verify.yml
    secrets: inherit

  documantaion:
    needs:
      - cache
      - analyze
      - verify
    if: >-
      ${{ !cancelled() &&
        (
          needs.cache.outputs.docs-updated != '0' ||
          github.event.inputs.force
        ) &&
        github.ref_name == github.event.repository.default_branch
      }}
    uses: ./.github/workflows/gen-docs.yml
    secrets: inherit

  save-status:
    needs:
      - cache
      - verify
    uses: ./.github/workflows/cache--save-status.yml
    if: ${{ always() }}
    with:
      status: ${{ needs.verify.result }}
