name: library-update
run-name: ${{ github.workflow }} (${{ github.ref_name }})

on:
  workflow_dispatch:
    inputs:
      force:
        type: boolean
        default: false
        required: true
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: update-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cache:
    if: ${{ !inputs.force }}
    uses: ./.github/workflows/load-prev-runs.yml

  quit:
    needs: cache
    if: needs.cache.outputs.verify-status == 'failure'
    runs-on: ${{ vars.RUNNER_IMAGE }}
    steps:
    - run: exit 1

  config:
    needs: cache
    if: ${{ !cancelled() }}
    runs-on: ${{ vars.RUNNER_IMAGE }}

    outputs:
      run-analysis: ${{ steps.set-vars.outputs.analysis }}
      run-verify: ${{ steps.set-vars.outputs.verify }}
      gen-docs: ${{ steps.set-vars.outputs.docs }}

    env:
      ANALYSIS: ${{ inputs.force || needs.cache.outputs.verify-status == '' }}

      VERIFY: >-
        ${{
          github.ref_name == github.event.repository.default_branch &&
          (
            inputs.force ||
            needs.cache.outputs.verify-status == '' ||
            needs.cache.outputs.verify-status == 'cancelled'
          )
        }}

      DOCS: >-
        ${{
          github.ref_name == github.event.repository.default_branch &&
          (inputs.force || needs.cache.outputs.docs-updated == true)
        }}

    steps:
      - name: Set variables
        id: set-vars
        run: |
          echo "Analysis: ${ANALYSIS}"
          echo "Verify: ${VERIFY}"
          echo "Docs: ${DOCS}"

          echo "analysis=${ANALYSIS}" >> ${GITHUB_OUTPUT}
          echo "verify=${VERIFY}" >> ${GITHUB_OUTPUT}
          echo "docs=${DOCS}" >> ${GITHUB_OUTPUT}

  analyze:
    needs: config
    if: ${{ !cancelled() && needs.config.outputs.run-analysis == 'true' }}
    uses: ./.github/workflows/analyze.yml

  verify:
    needs: config
    if: ${{ !cancelled() && needs.config.outputs.run-verify == 'true' }}
    uses: ./.github/workflows/verify.yml
    secrets: inherit

  documantaion:
    needs:
      - config
      - analyze
      - verify
    if: ${{ !cancelled() && needs.config.outputs.gen-docs == 'true' }}
    uses: ./.github/workflows/gen-docs.yml
    secrets: inherit

  post-cache:
    needs:
      - cache
      - verify
    uses: ./.github/workflows/save-verify-status.yml
    if: ${{ !cancelled() && needs.cache.result == 'success' && needs.verify.result != 'skipped' }}
    with:
      status: ${{ needs.verify.result }}
