name: library-update
run-name: ${{ github.workflow }} (${{ github.ref_name }})

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: update-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyze:
    uses: ./.github/workflows/analyze.yml

  verify:
    if: ${{ !cancelled() && github.ref_name == github.event.repository.default_branch }}
    uses: ./.github/workflows/verify.yml
    secrets: inherit

  documantaion:
    needs:
      - analyze
      - verify
    if: ${{ !cancelled() && github.ref_name == github.event.repository.default_branch }}
    uses: ./.github/workflows/gen-docs.yml
    secrets: inherit

  finalize:
    runs-on: ${{ vars.RUNNER_IMAGE }}

    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
      with:
        path: main
    
    - name: Compute hash
      run: |
        find ./main/ -type f -name '*.cpp' -or -name '*.hpp' | sort > ./file-list.txt
        cat ./file-list.txt | xargs sha1sum > ./cache-list.txt
        sha1sum ./cache-list.txt | sed 's/\s\s*.*$//g' > ./source-files-cache.txt

        echo "::group::Source files [cache: $(cat ./source-files-cache.txt)]"
        cat ./cache-list.txt;
        echo '::endgroup'
        
        cat ./source-files-cache.txt > ./cache-list.txt
        find ./main/.verify-helper/docs/ -type f | sort > ./file-list.txt
        cat ./file-list.txt | xargs sha1sum >> ./cache-list.txt
        sha1sum ./cache-list.txt | sed 's/\s\s*.*$//g' > ./docs-cache.txt

        echo "::group::Docs [cache: $(cat ./docs-cache.txt)]"
        cat ./cache-list.txt;
        echo '::endgroup'

    - name: Upload sorce code hash
      uses: actions/upload-artifact@v3
      with:
        name: source-code-hash
        path: ./source-files-cache.txt

    - name: Upload sorce code hash
      uses: actions/upload-artifact@v3
      with:
        name: docs-hash
        path: ./docs-cache.txt
