name: library-update
run-name: ${{ github.workflow }} (${{ github.ref_name }})

on:
  workflow_dispatch:
    inputs:
      force:
        type: boolean
        default: false
        required: true
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: update-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cache:
    if: ${{ !inputs.force }}
    uses: ./.github/workflows/load-prev-runs.yml

  quit:
    needs: cache
    if: needs.cache.outputs.verify-status == 'failure'
    runs-on: ${{ vars.RUNNER_IMAGE }}
    steps:
    - run: exit 1

  config:
    needs: cache
    runs-on: ${{ vars.RUNNER_IMAGE }}
    outputs:
      run-analyze: ${{ inputs.force || needs.cache.outputs.verify-status == '' }}
      run-verify: >-
        ${{
          github.ref_name == github.event.repository.default_branch &&
          (
            inputs.force ||
            needs.cache.outputs.verify-status == '' ||
            needs.cache.outputs.verify-status == 'cancelled'
          )
        }}
      gen-docs: >-
        ${{
          github.ref_name == github.event.repository.default_branch &&
          (inputs.force || needs.cache.outputs.docs-updated == true)
        }}
    steps:
      - run: exit 0

  analyze:
    needs: config
    if: ${{ !cancelled() && needs.config.outputs.run-analyze == 'true' }}
    uses: ./.github/workflows/analyze.yml

  verify:
    needs: config
    if: ${{ !cancelled() && needs.config.outputs.run-verify == 'true' }}
    uses: ./.github/workflows/verify.yml
    secrets: inherit

  documantaion:
    needs:
      - config
      - analyze
      - verify
    if: ${{ !cancelled() && needs.config.outputs.gen-docs == 'true' }}
    uses: ./.github/workflows/gen-docs.yml
    secrets: inherit

  post-cache:
    needs:
      - cache
      - verify
    uses: ./.github/workflows/save-verify-status.yml
    if: ${{ !cancelled() && needs.cache.result == 'succes' && needs.verify.result != 'skipped' }}
    with:
      status: ${{ needs.verify.result }}
