name: library-update
run-name: ${{ github.workflow }} (${{ github.ref_name }})

on:
  workflow_dispatch:
    inputs:
      force:
        type: boolean
        default: true
        required: true
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: update-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cache:
    if: ${{ ! github.event.inputs.force }}
    uses: ./.github/workflows/cache--load-status.yml

  analyze:
    needs: cache
    if: >-
      ${{
        !cancelled() &&
        (
          needs.cache.outputs.source-files-status != '' ||
          github.event.inputs.force
        )
      }}
    uses: ./.github/workflows/analyze.yml

  verify:
    needs: cache
    if: >-
      ${{
        !cancelled() &&
        (
          needs.cache.outputs.source-files-status != '' ||
          github.event.inputs.force
        ) &&
        github.ref_name == github.event.repository.default_branch
      }}
    uses: ./.github/workflows/verify.yml
    secrets: inherit

  documantaion:
    needs:
      - cache
      - analyze
      - verify
    if: >-
      ${{ !cancelled() &&
        (
          needs.cache.outputs.docs-status != '' ||
          github.event.inputs.force
        ) &&
        github.ref_name == github.event.repository.default_branch
      }}
    uses: ./.github/workflows/gen-docs.yml
    secrets: inherit

  get-status:
    needs: verify
    if: ${{ always() && ! github.event.inputs.force }}
    runs-on: ${{ vars.RUNNER_IMAGE }}
    steps:
      - name: Get status
        uses: technote-space/workflow-conclusion-action@v3

  save-statis:
    uses: ./.github/workflows/cache--save-status.yml
    with:
      status: ${{ env.WORKFLOW_CONCLUSION }}
