name: library-verification and documentation-generation

on:
  push:
    branch: main
  pull_request:

jobs:
  verify-and-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        path: main

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install dependencies
      run: pip3 install -U online-judge-verify-helper

    - name: Install AC-Library
      uses: actions/checkout@v3
      with:
        repository: atcoder/ac-library
        path: ac-library

    - name: Run tests
      working-directory: main
      env:
        CPLUS_INCLUDE_PATH: "${{ github.workspace }}/ac-library"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
      run:
        oj-verify all --jobs 3 --timeout 3600
