name: library-verification
run-name: ${{ github.workflow }} (${{ github.ref_name }})

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        id: ['00', '01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19']

    steps:

    - name: Git checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        path: main

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.0

    - name: Install oj-verify
      run: pip3 install -U online-judge-verify-helper

    - name: Clone AC-Library
      uses: actions/checkout@v3
      with:
        repository: atcoder/ac-library
        path: ac-library

    - name: Set C++ include path
      run:
        echo "CPLUS_INCLUDE_PATH=${{ github.workspace }}/ac-library" >> $GITHUB_ENV

    - name: Run tests
      working-directory: main
      env:
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        find verify -type f -name *.test.cpp | \
          awk -v n=${{ strategy.job-total }}  \
              -v i=${{ strategy.job-index }} \
              '{
                if((NR-1) % n == i) {
                  command = sprintf("oj-verify run %s --jobs 4 --timeout 3600", $0);
                  print command
                  system(command);
                  close(command);
                }
              }'
        cd .verify-helper
        mv ./timestamps.remote.json ./timestamps-${{ matrix.id }}.json
              
    - name: Save timestamps
      uses: actions/upload-artifact@v3
      with:
        name: timestamps
        path: main/.verify-helper/timestamps-${{ matrix.id }}.json

  post-verify:
    runs-on: ubuntu-latest
    needs: verify

    steps:
    - name: Git checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Git pull
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          git remote set-url origin https://${ GITHUB_ACTOR }:${ GITHUB_TOKEN }@github.com/${ GITHUB_REPOSITORY }
          git config --global user.name "GitHub"
          git config --global user.email "noreply@github.com"
          git pull origin main

    - name: Load timestamps
      uses: actions/download-artifact@v3
      with:
        path: .verify-helper/timestamps/

    - name: Merge timestamps
      working-directory: .verify-helper
      run: |
        jq -s 'reduce .[] as $item ({}; . * $item)' timestamps/timestamps/* > ./timestamps.remote.json
        cat ./timestamps.remote.json

    - name: Push timestamps
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          git remote set-url origin https://${ GITHUB_ACTOR }:${ GITHUB_TOKEN }@github.com/${ GITHUB_REPOSITORY }
          git config --global user.name "GitHub"
          git config --global user.email "noreply@github.com"
          if (git diff --shortstat | grep '[0-9]'); then \
            git pull origin main; \
            git add .; \
            git commit -m "[auto-verifier] verify commit ${GITHUB_SHA}"; \
            git push origin HEAD:${GITHUB_REF}; \
          fi

  gen-docs:
    runs-on: ubuntu-latest
    needs: post-verify

    steps:
    - name: Git checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        path: main

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.0

    - name: Install oj-verify
      run: pip3 install -U online-judge-verify-helper

    - name: Clone AC-Library
      uses: actions/checkout@v3
      with:
        repository: atcoder/ac-library
        path: ac-library

    - name: Set C++ include path
      run:
        echo "CPLUS_INCLUDE_PATH=${{ github.workspace }}/ac-library" >> $GITHUB_ENV

    - name: Generate documentation
      working-directory: main
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: oj-verify docs --jobs 4

