name: library-verification
run-name: ${{ github.workflow }} (${{ github.ref_name }})

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      YUKICODER_TOKEN:
        required: false
      GH_PAT:
        required: true

concurrency:
  group: verify-${{ github.ref }}
  cancel-in-progress: true

jobs:
  set-up:
    runs-on: ${{ vars.RUNNER_IMAGE }}

    outputs:
      node_ids: ${{ steps.collect.outputs.node_ids }}
      problems: ${{ steps.collect.outputs.problems }}

    steps:
    - name: Git checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Filter test files
      id: collect
      run: |
        set -eu

        N_PROC=$(nproc)

        if [ ! -f ./.verify-helper/timestamps.remote.json ]; then
          echo '{}' > ./.verify-helper/timestamps.remote.json
        fi

        echo -n > ./.verify-helper/problems.json
        echo -n > ./.verify-helper/allocation.json

        find verify -type f -name '*.test.cpp' | sort | \
        xargs -P ${N_PROC} -I {} bash ./.github/workflows/allocate.sh {}

        # find verify -type f -name '*.test.cpp' | sort > ./.verify-helper/allocation.json

        N_NODES=$(cat ./.verify-helper/allocation.json | wc -l)

        echo "::group::${N_NODES} test files allocated."
          cat ./.verify-helper/allocation.json
        echo "::endgroup::"
        echo

        if [ ${N_NODES} -gt 18 ]; then
          N_NODES=18
        fi

        echo "Tests are run on ${N_NODES} nodes."
        echo

        IDS='['
        for ((i=0; i < N_NODES; i++)); do
            IDS+=$(printf '"%02d"' "${i}")
            if [ $i -lt $((N_NODES-1)) ]; then
                IDS+=','
            fi
        done
        IDS+=']'

        echo "node_ids=$(echo "${IDS}" | jq -c)" >> ${GITHUB_OUTPUT}

        PROBLEMS="$(sort ./.verify-helper/problems.json | uniq | tr '\n' ',' | sed -e 's/,$/\n/g')"
        echo "[${PROBLEMS}]"

        echo "node_ids=$(echo "${IDS}" | jq -c)" >> ${GITHUB_OUTPUT}
        echo "problems=$(echo "[${PROBLEMS}]" | jq -c)" >> ${GITHUB_OUTPUT}

    - name: Save allocation list
      uses: actions/upload-artifact@v3
      with:
        name: allocation
        path: ./.verify-helper/allocation.json
        retention-days: 1

  gen-cases:
    runs-on: ${{ vars.RUNNER_IMAGE }}
    needs: set-up
    if: ${{ needs.set-up.outputs.node_ids != '[]' }}

    strategy:
      fail-fast: false
      matrix:
        problem: ${{ fromJSON(needs.set-up.outputs.problems) }}

    steps:
      - run: echo "${{ matrix.problem }}"

  run:
    runs-on: ${{ vars.RUNNER_IMAGE }}
    needs: gen-cases
    if: ${{ needs.set-up.outputs.node_ids != '[]' }}

    strategy:
      fail-fast: false
      matrix:
        id: ${{ fromJSON(needs.set-up.outputs.node_ids) }}

    steps:
    - name: Git checkout
      uses: actions/checkout@v3
      with:
        path: main
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.0

    - name: Install oj-verify
      run: pip3 install -U online-judge-verify-helper

    - name: Clone AC-Library
      uses: actions/checkout@v3
      with:
        repository: atcoder/ac-library
        path: ac-library
        sparse-checkout: atcoder

    - name: Load allocation list
      uses: actions/download-artifact@v3
      with:
        name: allocation
        path: ./main/.verify-helper/

    - name: Allocate test files
      working-directory: main
      env:
        CPLUS_INCLUDE_PATH: ${{ github.workspace }}/ac-library
      run: |
        TEST_FILES=$(
          cat ./.verify-helper/allocation.json  | \
          sort | \
          awk -v n=${{ strategy.job-total }} \
              -v i=${{ strategy.job-index }} \
              '{
                if((NR - 1) % n == i) {
                  print $0
                }
              }' \
          )

        echo ${TEST_FILES} > .verify-helper/targets.txt
        cat .verify-helper/targets.txt

    - name: Cache judge data
      if: ${{ !cancelled() && github.ref_name == github.event.repository.default_branch }}
      id: cache-judge
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/online-judge-tools/library-checker-problems/
          main/.verify-helper/cache/
        key: verify-${{ hashFiles('main/verify/**/*.test.cpp', 'main/.verify-helper/targets.txt') }}

    - name: Run tests
      working-directory: main
      env:
        CACHE_HIT: ${{ steps.cache-judge.outputs.cache-hit }}
        CPLUS_INCLUDE_PATH: ${{ github.workspace }}/ac-library
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
      run: |
        set -eu

        echo '{}' > ./.verify-helper/timestamps.json

        {
          if [ ! -f ./.verify-helper/timestamps.remote.json ] || [ "${CACHE_HIT}" != 'true' ]; then
            echo '{}' > ./.verify-helper/timestamps.remote.json
          fi

          sed -i '/^$/d' ./.verify-helper/timestamps.remote.json

          if -s ./.verify-helper/timestamps.remote.json; then
            echo '{}' >> ./.verify-helper/timestamps.remote.json
          fi
        }

        echo '::group::oj download prepare'
        oj download https://judge.yosupo.jp/problem/aplusb
        echo '::endgroup::'

        PARALLEL=$(nproc)
        echo "Parallel execution: ${PARALLEL}"

        head -c -1 ./.verify-helper/targets.txt | \
        xargs -P ${PARALLEL} -d ' ' -I {} bash ./.github/workflows/run-test.sh {}

        jq --slurp --sort-keys 'reduce .[] as $item ({}; . * $item)' \
        ./.verify-helper/timestamps.json > ./.verify-helper/temp.json

        cp -f ./.verify-helper/temp.json ./.verify-helper/timestamps.json

    - name: Save timestamps
      uses: actions/upload-artifact@v3
      if: ${{ !cancelled() }}
      with:
        name: test-${{ matrix.id }}
        path: main/.verify-helper/timestamps.json
        retention-days: 1

  post-run:
    runs-on: ${{ vars.RUNNER_IMAGE }}
    needs: run
    if: ${{ !cancelled() && github.ref_name == github.event.repository.default_branch }}

    steps:
    - name: Git checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        sparse-checkout: .verify-helper

    - name: Load timestamps
      uses: actions/download-artifact@v3
      with:
        # pattern: test-*
        path: .verify-helper/tests/

    - name: Merge timestamps
      working-directory: .verify-helper
      run: |
        touch ./timestamps.remote.json

        if ! ls ./tests/test-*/timestamps.json > /dev/null 2>&1; then
          echo "No timestamps found."
          exit 0
        fi

        jq --slurp --sort-keys 'reduce .[] as $item ({}; . * $item)' \
        ./timestamps.remote.json ./tests/test-*/timestamps.json > ./merged-timestamps.json

        cp -f ./merged-timestamps.json   ./timestamps.remote.json
        cat ./timestamps.remote.json

    - name: Push merged timestamps
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git remote set-url origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}

        git config --global user.name "GitHub"
        git config --global user.email "noreply@github.com"

        git add .verify-helper/timestamps.remote.json

        if (git diff --cached --shortstat | grep '[0-9]'); then
          git commit -m "[auto-verifier] verify commit ${GITHUB_SHA}"
          git pull --rebase
          git push origin HEAD:${GITHUB_REF}
        else
          echo "No timestamps updated."
        fi
