name: library-verification
run-name: ${{ github.workflow }} (${{ github.ref_name }})

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        id: [0, 1, 2, 3]

    steps:
    - name: Git checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        path: main

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.0

    - name: Install oj-verify
      run: pip3 install -U online-judge-verify-helper

    - name: Clone AC-Library
      uses: actions/checkout@v3
      with:
        repository: atcoder/ac-library
        path: ac-library

    - name: Set C++ include path
      run:
        echo "CPLUS_INCLUDE_PATH=${{ github.workspace }}/ac-library" >> $GITHUB_ENV

    - name: Run tests
      working-directory: main
      env:
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        find verify -type f -name *.test.cpp | \
          awk -v n=${{ strategy.job-total }}  \
              -v i=${{ strategy.job-index }} \
              '{ if((NR-1)%n == i) { system("oj-verify run $1 --jobs 4 --timeout 3600") } }'

  gen-docs:
    runs-on: ubuntu-latest
    needs: verify

    steps:
    - name: Git checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        path: main

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.0

    - name: Install oj-verify
      run: pip3 install -U online-judge-verify-helper

    - name: Clone AC-Library
      uses: actions/checkout@v3
      with:
        repository: atcoder/ac-library
        path: ac-library

    - name: Set C++ include path
      run:
        echo "CPLUS_INCLUDE_PATH=${{ github.workspace }}/ac-library" >> $GITHUB_ENV

    - name: Generate documentation
      working-directory: main
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: oj-verify docs --jobs 4

